server:
  port:
  servlet:
    context-path: /identity/api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "c8cvw7MIEv2x8O6rQ2C2cpVBiC0eN9iGUkLz/5BYx5gKrhmWEBTgYx6Gy0V1DaxD"