server:
  port:
  servlet:
    context-path: /identity/api/v1

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: ${SIGNER_KEY}
  token-ttl: 3600
  token-grace-period: 7200